# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java for publishing to GitHub Packages
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - name: Publish to GitHub Packages
      run: mvn -B -e package deploy -Dmaven.wagon.http.pool=false -DskipTests=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}